#!/bin/bash

# Bill table insertion
# Parameters: name, desc, nUpdates, nPages, fp, createdTime, updatedTime
function extract-bill() {
  printf "\e[1;31m$(date)  \e[1;32m$billId\e[0m - $title\n"
  local lastUpdateTm=$(sudo sqlite3 "$DB" "select lastUpdateTm from bill where name='$billId'")
  if [ -z "$lastUpdateTm" ]; then
    lastUpdateTm=0
  fi
  if [ $lastUpdateTm -lt $updateSecondsSinceEpoch ]; then
    # sqlite3 apparently doesn't support merge statements, so we'll delete and insert instead.
    execStr="
    sudo sqlite3 '$DB' '
    DELETE FROM bill
      WHERE name = \"$billId\";
    INSERT INTO bill (
      name,
      desc,
      lastUpdateTm,
      lastAction,
      lastActionDt,
      filepath,
      congress,
      chamber,
      file_ext)
    VALUES (
      \"$(echo $billId | tr -d "'")\",
      \"$(echo $title | tr -d "'")\",
      $updateSecondsSinceEpoch,
      \"$(echo $latestAction | tr -d "'")\",
      $latestActionDt,
      \"$(echo $textFp | tr -d "'")\",
      $congress,
      ( select id from chamber where lower( abbrev ) = lower(\"$chamber\") )
      \"${textFp##*.}\"
    );'"
    eval $execStr 
    if [ $? -ne 0 ]; then
      echo -e "Something went wrong with this sql insert statement. Debug it:\n\n\t$execStr"
      exit 1
    fi
  fi
}

